### ISSUE TITLE
Visualisation of DKPro KeyPhrases

### ISSUE THREAD

**Issue by globbestael** [dkpro/dkpro-keyphrases#41]
Hi DKPro,

Is the software for the visualisation for DKPro KeyPhrases available? Nicolai Erbs's thesis refers to https://dkpro.ukp.informatik.tu-darmstadt.de/DKProKeyphrases, the article "DKPro Keyphrases: Flexible and Reusable Keyphrase Extraction Experiments" to https://dkpro.ukp.informatik.tudarmstadt.de/DKProWebDemo/livedemo/3. Both sites can't be reached (timeout). 
I couldn't find the software on GitHub.

Best regards
geert

**Comment by reckart** [comment]
I believe the VM where that demo was running no longer exists - at least it was shut down. @nicolaierbs might be able to say more about the underlying code.

**Comment by nicolaierbs** [comment]
Unfortunately, the web demo is not online any longer, but I still have a version of the project on my private computer. If you send me an email to nicolai@privalino.de, I'm happy to share it with you.
